/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema_ollitas;

/**
 *
 * @author ANTHONY
 */
<<<<<<<< HEAD:SISTEMA_OLLITAS/src/sistema_ollitas/frmAdministrador.java
public class frmAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form frmAdministrador
     */
    public frmAdministrador() {
========
public class frmRegistrarOllitas extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistrarOllitas
     */
    public frmRegistrarOllitas() {
>>>>>>>> Bryan:SISTEMA_OLLITAS/src/sistema_ollitas/frmRegistrarOllitas.java
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
<<<<<<<< HEAD:SISTEMA_OLLITAS/src/sistema_ollitas/frmAdministrador.java
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboOpcionesAdmin = new javax.swing.JComboBox<>();
        btnIr = new javax.swing.JButton();
========
        txtNombre = new javax.swing.JTextField();
        txtDirección = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtContacto = new javax.swing.JTextField();
        btnRegistrarOllita = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
>>>>>>>> Bryan:SISTEMA_OLLITAS/src/sistema_ollitas/frmRegistrarOllitas.java

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

<<<<<<<< HEAD:SISTEMA_OLLITAS/src/sistema_ollitas/frmAdministrador.java
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Bienvenido al panel de Administradores");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 6, -1, -1));

        jLabel2.setText("Bienvenido al panel de Administradores");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 6, -1, -1));

        jLabel3.setText("Bienvenido al panel de Administradores");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 6, -1, -1));

        jLabel4.setText("Bienvenido al panel de Administradores");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 6, -1, -1));

        jLabel5.setText("Seleccione una Opcion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        cboOpcionesAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar Usuario", "Asignar Rol", "Registrar Ollita", "Editar Ollita", "Eliminar Ollita", "Cosultar Ollitas", "Registrar Insumo", "Editar Insumo", "Eliminar Insumo", "Consultar Inventario", "Registrar Donante", "Registrar Donación", "Editar Donación", "Eliminar Donación", "Consultar Donaciones", "Gestionar Solicitudes", "Historial de Entregas", "Registrar Evento Especial", "Agregar Observación a Ollita" }));
        jPanel1.add(cboOpcionesAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        btnIr.setText("IR");
        jPanel1.add(btnIr, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 220));
========
        jLabel1.setFont(new java.awt.Font("Consolas", 3, 36)); // NOI18N
        jLabel1.setText("Registrar Ollitas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 380, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel2.setText("Dirección");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 250, -1));
        getContentPane().add(txtDirección, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 250, -1));

        jLabel7.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel7.setText("Contacto Emergencia");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        getContentPane().add(txtContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 150, -1));

        btnRegistrarOllita.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        btnRegistrarOllita.setText("Registrar Ollita");
        getContentPane().add(btnRegistrarOllita, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 170, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 240));
>>>>>>>> Bryan:SISTEMA_OLLITAS/src/sistema_ollitas/frmRegistrarOllitas.java

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
<<<<<<<< HEAD:SISTEMA_OLLITAS/src/sistema_ollitas/frmAdministrador.java
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
========
            java.util.logging.Logger.getLogger(frmRegistrarOllitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarOllitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarOllitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarOllitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
>>>>>>>> Bryan:SISTEMA_OLLITAS/src/sistema_ollitas/frmRegistrarOllitas.java
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
<<<<<<<< HEAD:SISTEMA_OLLITAS/src/sistema_ollitas/frmAdministrador.java
                new frmAdministrador().setVisible(true);
========
                new frmRegistrarOllitas().setVisible(true);
>>>>>>>> Bryan:SISTEMA_OLLITAS/src/sistema_ollitas/frmRegistrarOllitas.java
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIr;
    private javax.swing.JComboBox<String> cboOpcionesAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
<<<<<<<< HEAD:SISTEMA_OLLITAS/src/sistema_ollitas/frmAdministrador.java
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
========
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JPasswordField txtDirección;
    private javax.swing.JTextField txtNombre;
>>>>>>>> Bryan:SISTEMA_OLLITAS/src/sistema_ollitas/frmRegistrarOllitas.java
    // End of variables declaration//GEN-END:variables
}
